# A simple Makefile for compiling small SDL projects

AllFile: 
	gcc -o theMan -L/opt/homebrew/lib/ -I/opt/homebrew/include/SDL2 -lSDL2 -lSDL2_image theMan.c
	gcc -o movingTheMan -L/opt/homebrew/lib/ -I/opt/homebrew/include/SDL2 -lSDL2 -lSDL2_image movingTheMan.c
clean: 
	rm *.o
	rm theGame